---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r loadlibraries}
Sys.setlocale("LC_TIME","English")
time <- format(Sys.time(), "%a %b %d %X %Y")
tz   <- Sys.timezone()
library(knitr)
library(dplyr)
setwd('C:/Users/acer/Developer/RepData_PeerAssessment1')
```

## Loading and preprocessing the data
```{r loaddata}
if(!file.exists("activity.csv")){
        unzip("activity.zip", exdir = ".")
}
activity <- read.csv("activity.csv", header = T, sep = ',')
# Convert date from factor into a date object.
activity$datePOSIX <- as.POSIXct(activity$date, format = "%Y-%m-%d", tz = "GMT")
```

## What is mean total number of steps taken per day?
```{r meantotal}
by_day <- group_by(activity, datePOSIX)
steps <- na.omit(summarise(by_day, Total = sum(steps)))
hist(steps$Total)
mean(steps$Total, na.rm = TRUE)
median(steps$Total, na.rm = TRUE)
```


## What is the average daily activity pattern?
```{r averagedaily}

activity$datetimePOSIX <- as.POSIXct(paste(activity$date, 
                                           sprintf("%04d", activity$interval)
                                           ),
                                     format="%Y-%m-%d %H%M", tz = "GMT")

by_datetime <- group_by(activity, datetimePOSIX)
steps_mean_dt <- na.omit(summarise(by_datetime, Average = mean(steps)))

plot(steps_mean_dt, type = "l", main = "Average Daily Activity Pattern")

steps_mean_dt[ which.max(steps_mean_dt$Average), ]
```


## Imputing missing values
```{r imputing}

```


## Are there differences in activity patterns between weekdays and weekends?
```{r differences}

```
